namespace TheorieMusique.Models
{
    public class LayoutViewModel
    {
        public List<string> Lexique { get; set; }

        public LayoutViewModel()
        {
            Lexique = new List<string>()
            {
                "accent;Un ¤accent sur une note signifie qu'on jouera cette note plus forte que les autres.",
                "accord parfait;Un ¤accord parfait est constitué de trois notes correspondant à une note ¤fondamentale + la ¤tierce et la ¤quinte de cette note.",
                "accords parfaits;Un ¤accord parfait est constitué de trois notes correspondant à une note ¤fondamentale + la ¤tierce et la ¤quinte de cette note.",
                "altération;Les ¤altérations de note les plus utilisées sont les ¤dieses et les ¤bémols. Les ¤dieses augmentent la note d'un ¤demi-ton et les ¤bémols baissent la note d'un ¤demi-ton.",
                "anticipant;Procédé consistant à ¤anticiper légèrement un événement musical attendu par l'auditeur. Le plus souvent, on ¤anticipe la ¤résolution d'une ¤tension.",
                "anticipation;Procédé consistant à ¤anticiper légèrement un événement musical attendu par l'auditeur. Le plus souvent, on ¤anticipe la ¤résolution d'une ¤tension.",
                "anticipe;Procédé consistant à ¤anticiper légèrement un événement musical attendu par l'auditeur. Le plus souvent, on ¤anticipe la ¤résolution d'une ¤tension.",
                "anticiper;Procédé consistant à ¤anticiper légèrement un événement musical attendu par l'auditeur. Le plus souvent, on ¤anticipe la ¤résolution d'une ¤tension.",
                "bémol;Altération d'une note pour la baisser d'un ¤demi-ton.",
                "binaire;Un rythme est ¤binaire quand sa ¤pulsation se divise en deux.",
                "blanche(2);¤Division rythmique. 2 ¤blanches valent 1 ¤ronde.",
                "blanches(2);¤Division rythmique. 2 ¤blanches valent 1 ¤ronde.",
                "conjoint;Un mouvement ¤conjoint est un mouvement mélodique dont les notes ne s'enchaînent qu'avec leurs notes les plus proches. Par exemple, DO-RE est un mouvement ¤conjoint, DO-SI également. Par contre, DO-MI est un mouvement ¤disjoint.",
                "croche(8);¤Division rythmique. 8 ¤croches valent 1 ¤ronde.",
                "croches(8);¤Division rythmique. 8 ¤croches valent 1 ¤ronde.",
                "DAW;Digital Audio Workspation. Terme utilisé pour désigner les logiciels comme Ableton Live, Cubase, Logic, FL Studio ou Reaper.",
                "degré;Les différents accords d'une ¤gamme sont désignés par leur ¤degré, c'est-à-dire la place de leur note ¤fondamentale. Par exemple, en ¤gamme de DO, la 2ère note est RE. L'accord de RE est donc l'accord du IIème ¤degré pour la ¤gamme de DO. On écrit généralement les ¤degrés en chiffres romains.",
                //" demi-ton;Un ¤demi-ton est le plus petit ¤intervalle qui existe entre deux notes, dans le cadre des musiques qui nous intéressent ici. Par exemple, DO et RE bémol sont séparés d'un demi-ton. Sur un piano, il n'existe pas de touche située entre DO et RE ¤bémol.",
                "demis-tons;Un ¤demi-ton est le plus petit ¤intervalle qui existe entre deux notes, dans le cadre des musiques qui nous intéressent ici. Par exemple, DO et RE bémol sont séparés d'un demi-ton. Sur un piano, il n'existe pas de touche située entre DO et RE ¤bémol.",
                "dephasing;Répétition d'un même ¤pattern en le décalant légèrement par rapport à celui de référence.",
                "diatonique;Un ¤mode ou une ¤gamme ¤diatonique est constitué de 7 notes.",
                "diese;Altération d'une note pour la monter d'un ¤demi-ton.",
                "disjoint;Un mouvement ¤disjoint est un mouvement mélodique dont les notes ne s'enchaînent jamais avec leurs notes les plus proches. Par exemple, DO-SOL est un mouvement ¤disjoint, DO-MI également. Par contre, DO-RE ou DO-SI sont des mouvement ¤conjoints.",
                "division;Pour ¤mesurer le rythme, on divise des durées. Par exemple, quand on divise la durée d'une ¤ronde en 4, on obtient 4 ¤noires. La ¤noire et la ¤ronde sont des ¤divisions rythmiques.",
                "dominante;C'est un terme spécifique à la ¤musique tonale. L'accord de ¤dominante est l'accord du Vème¤ degré.",
                "double-croche(16);¤Division rythmique. 16 ¤double-croches valent 1 ¤ronde.",
                "double-croches(16);¤Division rythmique. 16 ¤double-croches valent 1 ¤ronde.",
                "doubles-croches(16);¤Division rythmique. 16 ¤double-croches valent 1 ¤ronde.",
                "état fondamental;Un accord est à l'¤état fondamental quand sa note la plus grave est aussi sa note ¤fondamentale. Par exemple : DO MI SOL est un accord de DO à l'¤état fondamental.",
                "fondamentale;1ère note d'une ¤gamme. Par exemple, la note ¤fondamentale d'une ¤gamme de DO est la note DO.",
                "gamme;Une ¤gamme est un ¤mode construit sur une note ¤fondamentale.",
                "harmonie;Ensemble de règles conscientisées ou non pour la ¤polyphonie, c'est-à-dire la superposition de notes. L'¤harmonie dépend du contexte, comme par exemple l'époque, la culture ou le style.",
                "intensité;Force avec laquelle une événement musical est joué. Dans l'informatique musicale, le terme de ¤vélocité est employé, provenant du protocole ¤MIDI.",
                "intervalle;L'¤intervalle entre deux notes est le nombre de ¤demi-tons qui les sépare.",
                "liaison;Addition de deux valeurs rythmiques. Par exemple, deux ¤blanches(2) ¤liées forment la même durée qu'une ¤ronde(1).",
                "liéées;Addition de deux valeurs rythmiques. Par exemple, deux ¤blanches(2) ¤liées forment la même durée qu'une ¤ronde(1).",
                "MIDI;Le ¤MIDI est un protocole d'échange d'instructions entre instruments électroniques, ordinateurs compris.",
                "mode;Un ¤mode désigne les notes prédéfinies utilisées dans un morceau. Les ¤modes les plus courants sont soit ¤pentatoniques (constitués de 5 notes), soit ¤diatoniques (constitués de 7 notes).",
                "musique tonale;Musique à l'origine de la majorité des théories de la musique enseignées aujourd'hui, basée sur la musique de Bach. Les spécificités de la ¤musique tonale sont une rationalisation poussée des règles ¤harmoniques et l'utilisation de changements de gamme (nommés des ¤modulations). Elle concerne des musiques comme le classique, le jazz, la variété, le rock, le métal, les musiques orchestrales de films ou de jeux vidéos.",
                "musiques tonales;Musique à l'origine de la majorité des théories de la musique enseignées aujourd'hui, basée sur la musique de Bach. Les spécificités de la ¤musique tonale sont une rationalisation poussée des règles ¤harmoniques et l'utilisation de changements de gamme (nommés des ¤modulations). Elle concerne des musiques comme le classique, le jazz, la variété, le rock, le métal, les musiques orchestrales de films ou de jeux vidéos.",
                "noire(4);¤Division rythmique. 4 ¤noires valent 1 ¤ronde.",
                "noires(4);¤Division rythmique. 4 ¤noires valent 1 ¤ronde.",
                "n-olet;¤Division rythmique irrégulière par rapport au rythme général du morceau. N est une variable pouvant prendre plusieurs valeurs. Par exemple, un ¤triolet est une division ¤ternaire exceptionnelle au milieu d'un rythme ¤binaire.",
                "octave;L'¤octave est un ¤intervalle valant 6 ¤tons. On compte jusqu'à 8. Les deux notes sont considérées comme identiques. Exemple : entre DO et DO.",
                "pattern;Courte séquence musicale destinée à être répétée.",
                "pentatonique;Un ¤mode ou une ¤gamme ¤pentatonique est constitué de 5 notes. Il n'y a pas d'¤intervalle de ¤demi-ton entre ces notes.",
                "polyphonie;On parle de ¤polyphonie quand plusieurs notes sont superposées.",
                "pulsation;¤Division rythmique de référence à partir duquel est pensé le reste des ¤divisions. Pour la reconnaître : c'est la ¤division rythmique qu'on va battre du pied et des mains au long d'un morceau.",
                "quarte augmentée;La ¤quarte augmentée, aussi appelée ¤triton, est un ¤intervalle valant 3 ¤tons. On compte jusqu'à 4. Exemple : entre DO et FA ¤dièse.",
                "quarte diminuée;La ¤quarte diminuée est un ¤intervalle valant 2 ¤tons. On compte jusqu'à 4. Exemple : entre DO et FA ¤bémol.",
                "quarte;La ¤quarte est un ¤intervalle valant 2,5 ¤tons. On compte jusqu'à 4. Exemple : entre DO et FA.",
                "quinte diminuée;La ¤quinte diminuée, aussi appelée ¤triton, est un ¤intervalle valant 3 ¤tons. On compte jusqu'à 5. Exemple : entre DO et SOL ¤bémol.",
                "quinte;La ¤quinte est un ¤intervalle valant 3,5 ¤tons. On compte jusqu'à 5. Exemple : entre DO et SOL.",
                "renversement;Changement de l'ordre vertical des notes d'un accord. Par exemple, MI - SOL - DO est un ¤renversement de DO - MI - SOL.",
                "résolution;Retour à un état stable après une ¤tension (état instable). Par exemple : retour à la ¤consonnance après une ¤dissonance, ou retour à un rythme calé après un rythme décalé.",
                "retard ;Procédé consistant à ¤retarder légèrement un événement musical attendu par l'auditeur. Le plus souvent, on retarde la ¤résolution d'une ¤tension.",
                "ronde(1);La ¤ronde est la plus longue ¤division rythmique. Elle vaut 4 ¤noires. Les durées plus longues que la ¤ronde sont obtenues via des ¤liaisons. Par exemple, une ¤ronde liée à une ¤blanche forment une ¤division ayant la durée d'une ¤ronde et demi.",
                "rondes(1);La ¤ronde est la plus longue ¤division rythmique. Elle vaut 4 ¤noires. Les durées plus longues que la ¤ronde sont obtenues via des ¤liaisons. Par exemple, une ¤ronde liée à une ¤blanche forment une ¤division ayant la durée d'une ¤ronde et demi.",
                "seconde majeure;La ¤seconde majeure est un ¤intervalle valant 1 ¤ton. On compte jusqu'à 2. Exemple : entre DO et RE.",
                "seconde mineure;La ¤seconde mineure est un ¤intervalle valant 1/2 ¤ton. On compte jusqu'à 2. Exemple : entre MI et FA.",
                "sensible;C'est un terme spécifique à la ¤musique tonale. La ¤note sensible est la note située un ¤demi-ton en dessous de la ¤fondamentale.",
                "septième majeure;La ¤septième majeure est un ¤intervalle valant 5,5 ¤tons. On compte jusqu'à 7. Exemple : entre RE et DO ¤dièse.",
                "septième mineure;La ¤septième mineure est un ¤intervalle valant 5 ¤tons. On compte jusqu'à 7. Exemple : entre RE et DO.",
                "signature;Une ¤signature rythmique décrit la manière dont chaque ¤mesure est divisée. Elle s'écrit sous cette forme : Nombre de temps / valeur de chaque temps. Par exemple, avec la ¤signature 3/4, chaque ¤mesure est constituée de 3 ¤noires(4).",
                "sixte majeure;La ¤sixte majeure est un ¤intervalle valant 4,5 ¤tons. On compte jusqu'à 6. Exemple : entre FA et RE ¤dièse.",
                "sixte mineure;La ¤sixte mineure est un ¤intervalle valant 4 ¤tons. On compte jusqu'à 6. Exemple : entre FA et RE.",
                "sous-dominante;C'est un terme spécifique à la ¤musique tonale. L'accord de ¤sous-dominante est l'accord du IVème ¤degré.",
                "syncope;Procédé rythmique consistant à décaler sur les temps faibles un motif qui était joué sur les temps forts.",
                "tension;Création d'un état instable faisant désirer le retour à un état stable (qu'on nomme la ¤résolution). Par exemple : une ¤dissonance faisant désirer une ¤consonnance ou un décalage rythmique faisant désirer un retour sur les temps forts.",
                "ternaire;Un rythme est ¤ternaire quand sa ¤pulsation (et seulement sa ¤pulsation) se divise en trois",
                "tierce majeure;La ¤tierce mineure est un ¤intervalle valant 2 ¤tons. On compte jusqu'à 3. Exemple : entre DO et MI.",
                "tierce mineure;La ¤tierce mineure est un ¤intervalle valant 1,5 ¤ton. On compte jusqu'à 3. Exemple : entre RE et FA.",
                "timbre;Ensemble des propriétés d'un son permettant de le différencier des autres. Par exemple, lorsqu'un piano et une flûte jouent la même note à la même ¤intensité, ce qui différenciera les deux à l'oreille est leur ¤timbre.",
                //" ton ;Un ¤ton est constitué de deux ¤demi-tons. Par exemple, DO et RE sont séparés d'un ¤ton.",
                //" ton. ;Un ¤ton est constitué de deux ¤demi-tons. Par exemple, DO et RE sont séparés d'un ¤ton.",
                "tonalité;Terme spécifique à la ¤musique tonale. La ¤tonalité d'un morceau est sa ¤gamme principale, celle avec laquelle on va généralement démarrer et conclure ce morceau.",
                "tonique;C'est un terme spécifique à la ¤musique tonale. L'accord de ¤tonique est l'accord du Ier ¤degré.",
                //" tons ;Un ¤ton est constitué de deux ¤demi-tons. Par exemple, DO et RE sont séparés d'un ¤ton.",
                //" tons. ;Un ¤ton est constitué de deux ¤demi-tons. Par exemple, DO et RE sont séparés d'un ¤ton.",
                "transposition;Changement de gamme.",
                "triton;Le ¤triton est un ¤intervalle valant 3 tons. Exemple : entre FA et SI.",
                "vélocité;Nom donné à l'¤intensité d'un événement ¤MIDI dans l'informatique musicale."
            };
        }
    }
}
